name: Publish Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on tags like vX.Y.Z

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
        with:
          fetch-depth: 0  # Required for accessing tags

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
        with:
          go-version: stable

      # Step 3: Cache Go modules to speed up builds
      - name: Cache Go Modules
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Step 4: Extract Tag Name
      - name: Extract Tag Name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      # Step 5: Set Versioning Variables
      - name: Set Version Variables
        id: set_vars
        run: |
          echo "VERSION=${TAG_NAME}" >> $GITHUB_ENV

      # Step 6: Download dependencies
      - name: Download Dependencies
        run: make download-deps

      # Step 7: Build the application using Makefile with version info
      - name: Build
        run: make build VERSION=${VERSION}

      # Step 8: Create versioned archive
      - name: Create Versioned Archive
        run: |
          tar -czf "${TAG_NAME}.tar.gz" gospy

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@c9dc8369bccbc41e0ac887f8fd674f5925d315f7 # v5.4.1
        with:
          configuration: ".github/configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 9: Create a GitHub release
      - name: Create Release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{steps.build_changelog.outputs.changelog}}
          draft: false
          prerelease: false

      # Step 10: Upload the versioned archive to the release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.TAG_NAME }}.tar.gz
          asset_name: ${{ env.TAG_NAME }}.tar.gz
          asset_content_type: application/gzip
